name: Make a python package
on:
  push:
    branches:
    - '*'
    - '!master'
    
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Create a source distribution 
      run: >-
        build
        --sdist
        --outdir dist/
        .

